version: '3'
services:
  scoring_redis:
    container_name: scoring-redis
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - ${REDIS_VOLUME}:/data
    command: redis-server --appendonly yes
    restart: always
    networks:
        - scoring

  scoring_service:
    container_name: scoring-service
    image: eljoe182/cr-scoring:1.11.1
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - scoring_redis
    networks:
      - scoring

networks:
  scoring:
    name: scoring
    driver: bridge
