export * from './Attempts.contract';
export * from './ResultInfoCall.contract';
export * from './SaveHistoricData.contract';
export * from './SaveScoringData.contract';
export * from './IGetScoringParams'
export * from './INumberEvaluationParams'
export * from './ISaveScoringParams'
export * from './ISaveScoringResults'
export * from './IGetScoringResults'
