name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: package.json info
        id: pkg
        uses: jaywcjlove/github-action-package@main
      - run: echo "version - ${{ steps.pkg.outputs.version }}"
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $GITHUB_REPOSITORY:${{ steps.pkg.outputs.version }}

      - name: Docker Push
        run: docker push $GITHUB_REPOSITORY
